### ISSUE TITLE
Notes regarding compatibilty

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/EcosystemOverhaul#14]
## \- **Rename value with a unique, _different-from-vanilla_, name**

Something like _CK_BigCatThingBase_, _CK_BigCatKindBase_, etc

**Comment by lpCoercion** [comment]
This is a good idea, but we may eventually need to modify the vanilla animals as well to fit in with our new ecosystem (health, speed, damage, yield, etc.)

**Comment by lpCoercion** [comment]
BlueWinds is insisting on creating a version of this mod that is modular. He is asking for permission to do it if we dont. My response would be:

"If you want to create a version of this mod, split into its component parts (for other people to use) you can post a download link here and I will include it in the OP (assuming it is functional). You may not release another version of this mod elsewhere."

What are your thoughts/objections before I post this?

**Comment by lpCoercion** [comment]
So you know, I am also fine with just telling him "no" or just not answering the question.

**Comment by kaptain-kavern** [comment]
He often had good suggestions on my mods thread, I'm for seeing what he had in mind.

Me I have no problems with people doing whatever they want with what I do (I'm just reusing pieces of code), but I understand if you feel different with your works.

I asked him what he had in mind. It's sure that as a mod user I prefer modularity too, if possible.

As it still early in the development process it will be easier to reorganise files now rather than later ;-)

**Comment by lpCoercion** [comment]
He replied that he wants recipes separated. I am fine leaving recipes out (or somehow creating a future recipe patch), so it is up to you how we should proceed.

**Comment by lpCoercion** [comment]
I spoke with skullywag this morning. He said that: 1. we can reference item defs from other mods if they are loaded first and 2. recipes can be defined on the new item def itself (rather than the workstation), using "recipeuser". So, we could add the plants and ingredients in the base mod (e.g. cocoa plant, cocoa beans, vanilla, chiles, etc.) and then create future expansions:
- CK Animal Pack (plants & animals)
- CK Food and Drug Pack (food and drug recipes that reference ingredients from the main mod)
- CK Jurassic Pack (just be a new biomedefs and about file)

**Comment by kaptain-kavern** [comment]
That's pretty much what my reflections have bring as solution too. 

Basically no crafting in the base and all recipes in the F&D pack :package: 

I'm ok with that
