### ISSUE TITLE
Mounts and Animal Gear

### ISSUE THREAD

**Issue by lpCoercion** [kaptain-kavern/EcosystemOverhaul#25]
apparently killface is working on code that may allow animals to be mountable and wear armor. what are your thoughts on this? should we make add armor for tigers, gorillas, etc. mounts?

**Comment by kaptain-kavern** [comment]
In fact he ask me (and I suppose to other modders too) via pm to help him a bit, at least by testing it. So I will see in it when doing this, but I think i read he talks about removing saddle and mounted animals for now because of collision bug (because of the two pawns sitting in the same tile, or something similar I guess)

**Comment by lpCoercion** [comment]
oh ok. well let me know what happens with it. we can forget about it for now.
